name: build
on: [push]
jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Set Environment Variables
        run: |
          echo "runner_arch=$(uname -m)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          # install: true
          version: latest
          endpoint: builders
          buildkitd-flags: --debug
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path:  /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.runner_arch }}-buildx-${{ github.sha }}
          restore-keys:
            ${{ runner.os }}-${{ runner.arch }}-buildx-
      - name: Build in Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: local/temp:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - run: docker run -v $PWD/output:/mnt/output/ --rm temp sh -c "cp /work/*.deb /mnt/output/"
      - uses: actions/upload-artifact@v2
        with:
          name: built-packages
          path: "$PWD/output/*"
  publish:
    needs: build
    runs-on: [self-hosted, linux, AMD64]
    steps:
    - uses: actions/download-artifact@v2
    - run: ls -al
